"""empty message

Revision ID: a9976ebacea0
Revises: 9a59d5c2d614
Create Date: 2024-11-17 20:23:49.868530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9976ebacea0'
down_revision = '9a59d5c2d614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('homeworld',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               nullable=True)
        batch_op.create_foreign_key(None, 'planet', ['homeworld'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('homeworld',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
